---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/posts/{post_id}/comments":
    get:
      summary: Получить список комментариев
      tags:
      - Comments
      parameters:
      - name: post_id
        in: path
        required: true
        schema:
          type: integer
      - name: page
        in: query
        required: false
        schema:
          type: integer
      - name: items
        in: query
        required: false
        schema:
          type: integer
      responses:
        '200':
          description: список комментариев получен
          content:
            application/json:
              schema:
                type: object
                properties:
                  comments:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: integer
                        content:
                          type: string
                        author:
                          type: object
                          properties:
                            id:
                              type: integer
                            username:
                              type: string
                        created_at:
                          type: string
                          format: date-time
                  pagination:
                    type: object
                    properties:
                      count:
                        type: integer
                      page:
                        type: integer
                      items:
                        type: integer
                      pages:
                        type: integer
        '404':
          description: пост не найден
  "/posts":
    get:
      summary: returns all posts
      tags:
      - Posts
      responses:
        '200':
          description: posts found
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                    content:
                      type: string
                    author:
                      type: object
                      properties:
                        id:
                          type: integer
                        username:
                          type: string
                        first_name:
                          type: string
                        second_name:
                          type: string
                        last_name:
                          type: string
        '401':
          description: unauthorized
components:
  schemas:
    comment:
      type: object
      properties:
        id:
          type: integer
        content:
          type: string
        author:
          "$ref": "#/components/schemas/user"
        created_at:
          type: string
          format: date-time
        updated_at:
          type: string
          format: date-time
        parent_id:
          type: integer
          nullable: true
      required:
      - id
      - content
      - author
      - created_at
      - updated_at
    user:
      type: object
      properties:
        id:
          type: integer
        username:
          type: string
      required:
      - id
      - username
    pagination:
      type: object
      properties:
        count:
          type: integer
        page:
          type: integer
        items:
          type: integer
        pages:
          type: integer
      required:
      - count
      - page
      - items
      - pages
    error:
      type: object
      properties:
        error:
          type: string
      required:
      - error
    errors:
      type: object
      properties:
        errors:
          type: object
          additionalProperties:
            type: array
            items:
              type: string
      required:
      - errors
servers:
- url: http://{defaultHost}
  variables:
    defaultHost:
      default: 127.0.0.1:3000
